### ISSUE TITLE
conflict with redmine_issues_tree_view

### ISSUE THREAD

**Issue by archonwang** [two-pack/redmine_xlsx_format_issue_exporter#36]
https://github.com/charleneChen/redmine_issues_tree_view
it seems conflict with the plugin when I export the xlsx file.

please check it.
> https://github.com/charleneChen/redmine_issues_tree_view/issues/5

**Comment by two-pack** [comment]
redmine_issues_tree_view includes the patch of IssuesController, XLSX plugin too.
XLSX plugin uses alias_method_chain for the patch, so index method which is overwritten by XLSX plugin run after redmine_issues_tree_view's index method.
redmine_issues_tree_view is NOT support XLSX action, so occurred the error.

I try to fix changing how to patch. Maybe this problem is fixed.
But other plugins prepend before mine, this error may occur again.

**Comment by archonwang** [comment]
@two-pack 
Thanks. I will test it later.
