### ISSUE TITLE
stack level too deep error

### ISSUE THREAD

**Issue by kay54068** [two-pack/redmine_xlsx_format_issue_exporter#41]
hi ,
i get stack level too deep in redmine v3.3

**Comment by two-pack** [comment]
Please write detail of the problem, tracelog, version, your operation, etc.

**Comment by two-pack** [comment]
I canot repoduce error on Redmine 3.3.3.
Please write details with seeing following.
https://github.com/two-pack/redmine_xlsx_format_issue_exporter/wiki/How-to-report-issue

**Comment by martin-s** [comment]
1.What's happened?
Action: Click on Project issue page (e.g. http://localhost/redmine/projects/myrepo/issues)

2.What's problem?
HTTP GET returns error code 500

3.What do you want the result from this plugin?
It should display the issue page

4.How to reproduce the issue? If you cannot it, write step by step as known as possible.

5. MUST wirte Redmine information from Administration > Information.
Environment:
  Redmine version           3.3.3.stable
  Ruby version                 2.1.9-p490 (2016-03-30) [i386-mingw32]
  Rails version                  4.2.7.1
  Environment                  production
  Database adapter          Mysql2

Redmine plugins:
  a_common_libs                  2.3.0
  ajax_counters                  1.5.0
  extra_queries                  2.2.8
  global_roles                   2.2.0
  redmine_issue_tabs             1.2.3
  redmine_xlsx_format_issue_exporter 0.1.3
  rm_user_mentions               1.0.0
  unread_issues                  2.1.2

**Comment by two-pack** [comment]
This problem is caused with extra_queries plugin.
extra_queries plugin's issues_controller_patch.rb uses alias_method_chain, and XLSX format issue exporter uses prepend for patch.
This combination sometimes causes SystemStackError, see following links.

**alias_method_chain** will be deprecated on Rails 5, see https://github.com/rails/rails/pull/19434.
So I think this problem should be fixed by extra_queries plugin.

Note:
https://bugs.ruby-lang.org/issues/11120
http://eagletmt.hateblo.jp/entry/2016/02/17/201048
